{{ if .Values.webhook.createSelfSignedCert }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "selfsigned-issuer"
  namespace: {{ .Release.Namespace | quote }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-cert" (include "wiz-admission-controller.fullname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  subject:
    organizations:
    - wizselfsigned
  dnsNames:
  - {{ printf "%s.%s" (include "wiz-admission-controller-enforcer.name" .) .Release.Namespace | quote }}
  - {{ printf "%s.%s.svc" (include "wiz-admission-controller-enforcer.name" .) .Release.Namespace | quote }}
  - {{ printf "%s.%s" ( include "wiz-kubernetes-audit-log-collector.name" .) .Release.Namespace }}
  - {{ printf "%s.%s.svc" ( include "wiz-kubernetes-audit-log-collector.name" .) .Release.Namespace }}
  duration: "87600h0m0s" # AC doesn't currently detect changes to the certificate and must be restarted after renewal
  renewBefore: "360h0m0s"
  secretName: {{ include "wiz-admission-controller.secretServerCert" . | quote }}
    {{- if (or .Values.webhook.secret.annotations .Values.opaWebhook.secret.annotations) }}
  secretTemplate:
    annotations:
        {{- with .Values.webhook.secret.annotations }}
        {{- toYaml . | nindent 6 }}
        {{- end }}
        {{- with .Values.opaWebhook.secret.annotations }}
        {{- toYaml . | nindent 6 }}
        {{- end }}
    {{- end }}
  issuerRef:
    name: "selfsigned-issuer"
    kind: "Issuer"
    group: "cert-manager.io"
{{ end }}
