{{- if and .Values.hpa.enabled (eq (include "wiz-admission-controller.isEnforcerEnabled" . | trim | lower) "true") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wiz-hpa-enforcer.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiz-hpa-enforcer.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wiz-admission-controller.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    {{- if .Values.hpa.enableCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.hpa.enableMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .Values.hpa.customMetrics }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  behavior: {{ include "wiz-admission-controller.hpaBehavior" . | nindent 4 }}
---
{{- end }}
{{ if .Values.kubernetesAuditLogsWebhook.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wiz-hpa-audit-logs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiz-hpa-audit-logs.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wiz-kubernetes-audit-log-collector.name" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    {{- if .Values.hpa.enableCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.hpa.enableMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .Values.hpa.customMetrics }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  behavior: {{ include "wiz-admission-controller.hpaBehavior" . | nindent 4 }}
{{- end }}
