{{- if .Values.networkPolicy.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wiz-admission-controller.fullname" . }}-policy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-admission-controller.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "wiz-admission-controller.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress: []
{{- end }}
