{{- $tlsCrt := .Values.tlsCertificate.tlsCertificate -}}
{{- $tlsKey := .Values.tlsCertificate.tlsKey -}}
{{- if .Values.tlsCertificate.create -}}
{{- $altNames := list ( printf "%s.%s" (include "wiz-admission-controller.fullname" .) .Release.Namespace ) ( printf "%s.%s.svc" (include "wiz-admission-controller.fullname" .) .Release.Namespace ) -}}
{{- $ca := genCA "wiz-admission-controller-ca" 3650 -}}
{{- $cert := genSignedCert ( include "wiz-admission-controller.fullname" . ) nil $altNames 3650 $ca -}}
{{- $tlsCrt = $cert.Cert | b64enc -}}
{{- $tlsKey = $cert.Key | b64enc -}}
{{- end -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "wiz-admission-controller.fullname" . }}
  labels:
    {{- include "wiz-admission-controller.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
webhooks:
- name: wizadmissionvalidator.wiz.io
  admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "wiz-admission-controller.fullname" . }}
      path: /opa-validator
      port: {{ .Values.service.port }}
    caBundle: {{ $tlsCrt }}
  {{- with .Values.opaWebhook.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.opaWebhook.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  failurePolicy: {{ .Values.opaWebhook.failurePolicy }}
  sideEffects: {{ .Values.opaWebhook.sideEffects }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "wiz-admission-controller.secretServerCert" . | trim }}
  labels:
    {{- include "wiz-admission-controller.labels" . | nindent 4 }}
  annotations:
    # Using helm hook to create certs only for chart install
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- with .Values.opaWebhook.secret.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  tls.crt: {{ $tlsCrt }}
  tls.key: {{ $tlsKey }}
