{{- if .Values.httpProxyConfiguration.enabled }}
{{- if .Values.httpProxyConfiguration.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-admission-controller.proxySecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-admission-controller.labels" . | nindent 4 }}
  {{- with .Values.httpProxyConfiguration.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  httpProxy: {{ .Values.httpProxyConfiguration.httpProxy | quote }}
  httpsProxy: {{ .Values.httpProxyConfiguration.httpsProxy | quote }}
  noProxyAddress: {{ .Values.httpProxyConfiguration.noProxyAddress | quote }}
{{- end }}
{{- end }}
