{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wiz-admission-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-admission-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{ if and .Values.imageIntegrityWebhook.enabled .Values.imageRegistyClient.pullSecrets .Values.imageRegistyClient.createRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-pull-secrets-reader" (include "wiz-admission-controller.serviceAccountName" .) }}
  namespace: {{ .Values.imageRegistyClient.secretsNamespace | quote }}
  labels:
    {{- include "wiz-admission-controller.labels" . | nindent 4 }}
  rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: {{ .Values.imageRegistyClient.pullSecrets | toJson }}
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-pull-secrets-reader" (include "wiz-admission-controller.serviceAccountName" .) }}
  namespace: {{ .Values.imageRegistyClient.secretsNamespace | quote }}
  labels:
    {{- include "wiz-admission-controller.labels" . | nindent 4 }}
  subjects:
  - kind: ServiceAccount
    name: {{ include "wiz-admission-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
  roleRef:
    kind: Role
    name: {{ printf "%s-pull-secrets-reader" (include "wiz-admission-controller.serviceAccountName" .) }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
