{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agentCredsSecretName }}
  labels:
    {{- include "wiz-outpost-configuration.labels" . | nindent 4 }}
  {{- if .Values.agent.annotations }}
  annotations: {{ toYaml .Values.agent.annotations | nindent 4 }}
  {{- end }}

stringData:
{{- if .Values.agent.clientId }}
  clientId: {{ required "Missing required value agent.clientId is required" .Values.agent.clientId | quote }}
  clientSecret: {{ required "Missing required value: agent.clientSecret is required" .Values.agent.clientSecret | quote }}
{{- else }}
  privateKey: {{ required "Missing required value agent.privateKey" .Values.agent.privateKey | quote }}
{{- end }}
{{- end }}
