{{- if .Values.azureCreds }}
{{/* Small hack for autoamated clusters - publish the secret for git-proxy / external secrets */}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: azure-creds
  labels:
    {{- include "wiz-outpost-configuration.labels" . | nindent 4 }}
data:
  azure.json: {{ .Values.azureCreds | toJson | b64enc | quote }}
  # external secrets need each key separately so we reference the secret via env vars
  {{- range $k, $v := .Values.azureCreds }}
  {{- if and (not (eq $k "useInstanceMetadata" )) (not (eq $k "useFederatedToken" ))}}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
