{{- if and .Values.outpostController.enabled .Values.outpostController.reducedPermissions }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "wiz-outpost-configuration.fullname" . }}-outpost-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wiz-outpost-configuration.labels" . | nindent 4 }}
    app.kubernetes.io/component: outpost-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "wiz-outpost-configuration.fullname" . }}-outpost-controller
subjects:
- kind: ServiceAccount
  name: {{ .Values.outpostController.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end }}
