{{- if and .Values.outpostController.enabled .Values.outpostController.reducedPermissions }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wiz-outpost-configuration.fullname" . }}-outpost-controller
  labels:
    {{- include "wiz-outpost-configuration.labels" . | nindent 4 }}
    app.kubernetes.io/component: outpost-controller
rules:
  # Doctor diagnostics - read-only cluster access for node health checks
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
{{- end }}
