{{- if .Values.serviceAccount.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wiz-sensor.fullname" . }}
  labels: {{- include "wiz-sensor.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "wiz-sensor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "wiz-sensor.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
