{{- include "validate.values" . }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "wiz-sensor.fullname" . }}
  labels: {{- include "wiz-sensor.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    matchLabels: {{- include "wiz-sensor.selectorLabels" . | nindent 6 }}

  updateStrategy:
{{ toYaml .Values.daemonset.updateStrategy | indent 4 }}

  template:
    metadata:
      labels: {{- include "wiz-sensor.labels" . | nindent 8 }}

      annotations:
      {{- if .Values.exposeMetrics }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.metricsPort }}"
      {{- end }}

      {{- if semverCompare "<1.31-0" .Capabilities.KubeVersion.GitVersion }}
        container.apparmor.security.beta.kubernetes.io/wiz-sensor: unconfined
      {{- end }}
        cluster-autoscaler.kubernetes.io/enable-ds-eviction: "true"
        {{- with (coalesce .Values.global.podAnnotations (coalesce .Values.daemonset.podAnnotations .Values.podAnnotations)) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "wiz-sensor.serviceAccountName" . }}
      {{- end }}

      {{- with (coalesce .Values.global.nodeSelector .Values.daemonset.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.daemonset.priorityClassName }}
      priorityClassName: {{ .Values.daemonset.priorityClassName }}
      {{- end }}

      {{- with (coalesce .Values.global.affinity .Values.daemonset.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}

      hostPID: true
      hostIPC: true

      {{- with (coalesce .Values.global.tolerations .Values.daemonset.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      restartPolicy: Always

      containers:
      {{- if .Values.diskScan.enabled }}
      - name: wiz-disk-scanner
        {{- if (coalesce .Values.global.image.registry .Values.image.registry) }}
        image: {{ printf "%s/%s:%s" (coalesce .Values.global.image.registry .Values.image.registry) .Values.image.diskScanRepository .Values.image.diskScanTag }}
        {{- else }}
        image: {{ printf "%s:%s" .Values.image.diskScanRepository .Values.image.diskScanTag }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.diskScanPullPolicy }}
        {{- with .Values.image.diskScanArgs }}
        args:
          {{- toYaml . | nindent 8 }}
        {{- end }}

        securityContext:
        {{- if .Values.privileged }}
          privileged: true
          runAsUser: 0
          runAsGroup: 0
        {{- else }}
          capabilities:
            add:
            - SYS_ADMIN  # Mounting host filesystem as read only.
            - DAC_READ_SEARCH # file reading
            - SETPCAP # Dropping capabilities when not needed
          privileged: false
          runAsNonRoot: true
          runAsUser: 2202
          runAsGroup: 2202
        {{- end }}
          readOnlyRootFilesystem: true
          {{- if semverCompare ">=1.31-0" .Capabilities.KubeVersion.GitVersion }}
          appArmorProfile:
            type: Unconfined
          {{- end }}
          {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
          seccompProfile:
            type: Unconfined
          {{- end }}
          seLinuxOptions:
            user: "system_u"
            role: "system_r"
            level: "s0"
            {{- if .Values.flatcarLinuxNodes }}
            type: "unconfined_t"
            {{- else }}
            type: "spc_t"
            {{- end }}

        env:
        - name: POD_MEM_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: wiz-disk-scanner
              resource: limits.memory
              divisor: "1Mi"
        - name: POD_CPU_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: wiz-disk-scanner
              resource: limits.cpu
              divisor: "1m"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if (or .Values.global.httpProxyConfiguration.enabled .Values.httpProxyConfiguration.enabled) }}
        - name: https_proxy # Used by Go runtime to set https proxy
          valueFrom:
            secretKeyRef:
              name: {{ include "wiz-sensor.proxySecretName" . }}
              key: httpsProxy
        - name: SSL_CERT_DIR # Used by Go runtime to resolve additional certificates from this directory
          value: "/proxy-config"
        {{- end }}
        {{- if .Values.startDelayRange }}
        - name: WIZ_ONPREM_ORCHESTRATOR_MAX_JITTER_DELAY
          value: "{{ .Values.startDelayRange }}s"
        {{- end }}
        - name: WIZ_BACKEND_ENV
          valueFrom:
            secretKeyRef:
              name: {{ include "wiz-sensor.secretName" . }}
              key: clientEndpoint
              optional: true
        - name: WIZ_ONPREM_SCANNER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ include "wiz-sensor.diskScanConfigName" . }}
              key: config

        {{- with .Values.podCustomEnvironmentVariables }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.podCustomEnvironmentVariables }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

        volumeMounts:
        {{- with .Values.customVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.customVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: host-mount
          mountPath: /host
          readOnly: true
          {{- if semverCompare ">=1.30-0" .Capabilities.KubeVersion.GitVersion }}
          recursiveReadOnly: IfPossible
          {{- end }}
        - name: api-client-secret
          mountPath: /api-client/
        - name: api-endpoint-name-secret
          mountPath: /api-endpoint-name/
        - name: sensor-scanner-shared-vol
          mountPath: /wiz-sensor-share/
        - name: sensor-scanner-tmp-store
          mountPath: /tmp/
        {{- if (or .Values.global.httpProxyConfiguration.enabled .Values.httpProxyConfiguration.enabled) }}
        - name: proxy-secret
          mountPath: /proxy-config/
        {{- end }}

        {{- if .Values.daemonset.resources }}
        resources:
          {{- if .Values.daemonset.resources.diskScanLimits }}
          limits:
{{ toYaml .Values.daemonset.resources.diskScanLimits | indent 12 }}
          {{- end }}
          {{- if and (not .Values.gkeAutopilot) .Values.daemonset.resources.diskScanRequests }}
          requests:
{{ toYaml .Values.daemonset.resources.diskScanRequests | indent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}

      - name: wiz-sensor
        {{- if (coalesce .Values.global.image.registry .Values.image.registry) }}
        image: {{ printf "%s/%s:%s" (coalesce .Values.global.image.registry .Values.image.registry) .Values.image.repository .Values.image.tag }}
        {{- else }}
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
        {{- end }}
        imagePullPolicy: {{ coalesce .Values.global.image.pullPolicy .Values.image.pullPolicy }}
        {{- with .Values.image.args }}
        args:
          {{- toYaml . | nindent 8 }}
        {{- end }}

        {{- if .Values.exposeMetrics }}
        ports:
        - containerPort: {{ .Values.metricsPort }}
          name: metrics
          protocol: TCP
        {{- end }}

        securityContext:
        {{- if .Values.privileged }}
          privileged: true
          runAsUser: 0
          runAsGroup: 0
        {{- else }}
          capabilities:
            add:
            - SYS_ADMIN # moving between namespaces
            - SYS_CHROOT # moving between namespaces
            - SYS_RESOURCE # eBPF
            - SYS_RAWIO # file hashing
            - DAC_OVERRIDE # file hashing
            - DAC_READ_SEARCH # file hashing
            - NET_ADMIN # network events
            - NET_RAW # network events
            - IPC_LOCK # eBPF
            - FOWNER # file hashing
            - SYS_PTRACE # eBPF
          {{- if not .Values.gkeAutopilot }}
            - SYSLOG # kernel symbol resolve
          {{- end }}
          {{- if not .Values.disallowRuntimeResponse }}
            - KILL # response
          {{- end }}
          {{- if .Values.disallowRuntimeResponse }}
            drop:
            - KILL # response
          {{- end }}
          privileged: false
          runAsNonRoot: true
          runAsUser: 2202
          runAsGroup: 2202
        {{- end }}
          readOnlyRootFilesystem: true

          {{- if semverCompare ">=1.30-0" .Capabilities.KubeVersion.GitVersion }}
          appArmorProfile:
            type: Unconfined
          {{- end }}

          {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
          seccompProfile:
            type: Unconfined
          {{- end }}
          seLinuxOptions:
            user: "system_u"
            role: "system_r"
            level: "s0"
            {{- if .Values.flatcarLinuxNodes }}
            type: "unconfined_t"
            {{- else }}
            type: "spc_t"
            {{- end }}

        env:
        {{- if not .Values.gkeAutopilot }}
        - name: MIN_SENSOR_COMPAT_BUILD_VER
          value: "4142"
        - name: HELM_CHART_COMPAT_VER
          value: "1"
        {{- end }}
        - name: WIZ_TMP_STORE
          value: "/wiz-sensor-store/"
        - name: WIZ_HOST_STORE
        {{- if .Values.daemonset.sensorHostCacheCreate }}
          value: "/wiz-host-cache/"
        {{- else }}
          value: "/wiz-sensor-store/"
        {{- end }}
        - name: WIZ_RAMFS_STORE
          value: "/tmp/"
        - name: LOG_FILE
          value: "/wiz-sensor-store/sensor.log"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_APIKEY_SECRET_NAME
          value: {{ include "wiz-sensor.secretName" . }}
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
        - name: CRI_SOCKET_CUSTOM_PATH
          value: {{ .Values.daemonset.criSocketPath }}
        - name: HTTP_PROXY_URL
          value: {{ .Values.daemonset.httpProxyUrl }}
        - name: HTTP_PROXY_USERNAME
          value: {{ .Values.daemonset.httpProxyUsername }}
        - name: HTTP_PROXY_PASSWORD
          value: {{ .Values.daemonset.httpProxyPassword }}
        - name: HTTP_PROXY_CERT
          value: {{ .Values.daemonset.httpProxyCaCert }}
        {{- if .Values.diskScan.enabled }}
        - name: DISK_SCAN_SHARED_VOL
          value: "/wiz-sensor-share/"
        {{- end }}
        {{- if .Values.ciMode }}
        - name: CI_MODE
          value: "true"
        {{- end }}
        - name: BACKEND_ENV
          value: {{ coalesce .Values.global.wizApiToken.clientEndpoint .Values.wizApiToken.clientEndpoint .Values.backendEnv "prod" }}
        {{- if and (not .Values.gkeAutopilot) .Values.tenantSuffix }}
        - name: TENANT_SUFFIX
          value: {{ .Values.tenantSuffix }}
        {{- end }}
        - name: SENSOR_CLUSTER_NAME
          value: {{ .Values.sensorClusterName }}
        - name: RUST_LOG
          value: {{ include "wiz-sensor.fileLogLevel" . }}
        - name: STDOUT_LOG
          value: {{ include "wiz-sensor.stdoutLogLevel" . }}
        - name: POD_MEM_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: wiz-sensor
              resource: limits.memory
              divisor: "1Mi"
        - name: POD_CPU_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: wiz-sensor
              resource: limits.cpu
              divisor: "1m"
        {{- if .Values.disallowRuntimeResponse }}
        - name: DISALLOW_RUNTIME_RESPONSE
          value: "true"
        {{- end}}
        {{- if .Values.startDelayRange }}
        - name: SENSOR_START_DELAY_RANGE
          value: {{ quote .Values.startDelayRange }}
        {{- end}}
        {{- if coalesce .Values.global.clusterExternalId .Values.clusterExternalId }}
        - name: CLUSTER_EXTERNAL_ID
          value: {{ coalesce .Values.global.clusterExternalId .Values.clusterExternalId }}
        {{- end }}
        {{- if .Values.exposeMetrics }}
        - name: METRICS_PORT
          value: "{{ .Values.metricsPort }}"
        {{- end }}
        {{- with .Values.podCustomEnvironmentVariables }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.podCustomEnvironmentVariables }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

        volumeMounts:
        {{- with .Values.customVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.customVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.daemonset.sensorHostCacheCreate }}
        - name: sensor-host-cache
          mountPath: /wiz-host-cache/
        {{- end }}
        - name: sensor-store
          mountPath: /wiz-sensor-store/
        - name: tmp-store
          mountPath: /tmp/
        - name: api-client-secret
          mountPath: /api-client/
        {{- if not .Values.gkeAutopilot }}
        - name: api-endpoint-name-secret
          mountPath: /api-endpoint-name/
        {{- end }}
        {{- if .Values.diskScan.enabled }}
        - name: sensor-scanner-shared-vol
          mountPath: /wiz-sensor-share/
        {{- end }}
        {{- if (or .Values.global.httpProxyConfiguration.enabled .Values.httpProxyConfiguration.enabled) }}
        - name: proxy-secret
          mountPath: /proxy-config/
        - name: proxy-client-cert-secret
          mountPath: /proxy-client-config/
        {{- end }}

        {{- if .Values.daemonset.resources }}
        resources:
          {{- if .Values.daemonset.resources.limits }}
          limits:
{{ toYaml .Values.daemonset.resources.limits | indent 12 }}
          {{- end }}
          {{- if and (not .Values.gkeAutopilot) .Values.daemonset.resources.requests }}
          requests:
{{ toYaml .Values.daemonset.resources.requests | indent 12 }}
          {{- end }}
        {{- end }}

      terminationGracePeriodSeconds: {{ .Values.daemonset.terminationGracePeriodSeconds }}
      {{- if .Values.imagePullSecret.required }}
      imagePullSecrets:
        {{ include "wiz-sensor.imagePullSecretList" . }}
      {{- end }}
      volumes:
      {{- with .Values.customVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.global.customVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.daemonset.sensorHostCacheCreate }}
      - name: sensor-host-cache
        hostPath:
          path: {{ .Values.daemonset.sensorHostCacheFolder }}
          type: DirectoryOrCreate
      {{- end }}
      - name: api-client-secret
        secret:
          secretName: {{ include "wiz-sensor.secretName" . }}
          items:
            - key: clientId
              path: clientId
            - key: clientToken
              path: clientToken
      {{- if not .Values.gkeAutopilot }}
      - name: api-endpoint-name-secret
        secret:
          secretName: {{ include "wiz-sensor.secretName" . }}
          optional: true
          items:
            - key: clientEndpoint
              path: clientEndpoint
      {{- end }}
      {{- if (or .Values.global.httpProxyConfiguration.enabled .Values.httpProxyConfiguration.enabled) }}
      - name: proxy-secret
        secret:
          secretName: {{ include "wiz-sensor.proxySecretName" . }}
          items:
            - key: httpsProxy
              path: https-proxy
            - key: caCertificate
              path: ca-cert
      - name: proxy-client-cert-secret
        secret:
          secretName: {{ include "wiz-sensor.proxySecretName" . }}
          optional: true
          items:
            - key: clientCertificate
              path: client-cert
      {{- end }}
      - name: sensor-store
        emptyDir:
          sizeLimit: "1Gi"
      - name: tmp-store
        emptyDir:
          sizeLimit: "100Mi"
          medium: "Memory"
      {{- if .Values.diskScan.enabled }}
      - name: host-mount
        hostPath:
          path: /
      - name: sensor-scanner-shared-vol
        emptyDir:
          sizeLimit: "100Mi"
          medium: "Memory"
      - name: sensor-scanner-tmp-store
        emptyDir:
          sizeLimit: "200Mi"
          medium: "Memory"
      {{- end }}
