{{- if and .Values.imagePullSecret.required .Values.imagePullSecret.create -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "wiz-sensor.imagePullSecretName" . }}
  labels: {{- include "wiz-sensor.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ template "wiz-sensor.imagePullSecretValue" . }}
{{- end -}}
