{{- if .Values.serviceAccount.rbac -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "wiz-sensor.fullname" . }}-namespace-rolebinding
  labels: {{- include "wiz-sensor.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "wiz-sensor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "wiz-sensor.fullname" . }}-namespace-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
