{{- if and (not (empty .Values.global.httpProxyConfiguration.httpsProxy)) (eq .Values.global.httpProxyConfiguration.enabled false) }}
  {{- fail "Error: httpsProxy is set but httpProxyConfiguration.enabled is false. Please enable the proxy configuration or unset httpsProxy." }}
{{- end }}

{{- if and .Values.global.httpProxyConfiguration.enabled .Values.global.httpProxyConfiguration.create }}
  {{- if hasPrefix "https://" .Values.global.httpProxyConfiguration.httpsProxy }}
    {{- fail "Error: httpsProxy must start with 'http://', https or any other protocol is not supported." }}
  {{- end }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-kubernetes-integration.proxySecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  {{ if or (index .Values "wiz-kubernetes-connector" "enabled") .Values.global.httpProxyConfiguration.annotations }}
  annotations:
    {{- if (index .Values "wiz-kubernetes-connector" "enabled") }} # Secret used by per-install hook in wiz-kubernetes-connector
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- end }}
    {{- with .Values.global.httpProxyConfiguration.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "wiz-kubernetes-integration.labels" . | nindent 4 }}
stringData:
  httpProxy: {{ .Values.global.httpProxyConfiguration.httpProxy | quote }}
  httpsProxy: {{ .Values.global.httpProxyConfiguration.httpsProxy | quote }}
  noProxyAddress: {{ .Values.global.httpProxyConfiguration.noProxyAddress | quote }}
  caCertificate: {{ .Values.global.httpProxyConfiguration.caCertificate | quote }}
{{- end }}
