{{- if and .Values.global.httpProxyConfiguration.enabled .Values.global.httpProxyConfiguration.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-kubernetes-integration.proxySecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.global.httpProxyConfiguration.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wiz-kubernetes-integration.labels" . | nindent 4 }}
data:
  httpProxy: {{ .Values.global.httpProxyConfiguration.httpProxy | b64enc | quote }}
  httpsProxy: {{ .Values.global.httpProxyConfiguration.httpsProxy | b64enc | quote }}
  noProxyAddress: {{ .Values.global.httpProxyConfiguration.noProxyAddress | b64enc | quote }}
{{- end }}
