# Default values for outpost-lite.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

agent:
  secretName: outpost-lite-agent-creds
  env: ""
  clientId: ""
  clientSecret: ""
  outpostId: ""
  outpostRegion: region-1

secret:
  create: true

image:
  repository: wizio.azurecr.io
  namePrefix: outpost-lite-runner
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ea3b7b48a77b74f9adfd5e0a48569a1bea7bee4d-multiarch"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  limits:
    memory: 4396M
  requests:
    memory: 1024M

nodeSelector: {}

tolerations: []

affinity: {}

internetAccessCertificates:
  skipSslValidation: false

extraEnv: {}

httpProxyConfiguration:
  name: wiz-http-proxy-configuration
