apiVersion: v2
name: wiz-sensor
description: Wiz Sensor helm chart
type: application
home: https://www.wiz.io/
version: 1.0.11006
appVersion: 1.0.10715
annotations:
  diskScanAppVersion: 1.1.49
  windowsAppVersion: 1.0.10902