apiVersion: v2
name: wiz-sensor
description: Wiz Sensor helm chart
type: application
home: https://www.wiz.io/
version: 1.0.11181
appVersion: 1.0.11181
annotations:
  diskScanAppVersion: 1.1.50
  windowsAppVersion: 1.0.10902