apiVersion: v2
name: wiz-sensor
description: Wiz Sensor helm chart
type: application
home: https://www.wiz.io/
version: 1.0.11492
appVersion: 1.0.11492
annotations:
  diskScanAppVersion: 1.1.52
  windowsAppVersion: 1.0.11446