apiVersion: v2
name: "wiz-broker"
description: Wiz Broker for tunneling http traffic to Wiz backend

type: application

version: 2.2.6-preview.8
appVersion: "2.6"

dependencies:
  - name: wiz-common
    version: "0.1.0"
    repository: https://wiz-sec.github.io/charts
    #    repository: "file://../wiz-common" # Use this line to test the chart locally
