{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agent.secretName }}
  labels:
    {{- include "wiz-outpost-lite.labels" . | nindent 4 }}
stringData:
{{- if .Values.agent.clientId }}
  clientId: {{ required "Missing required value agent.clientId is required" .Values.agent.clientId | quote }}
  clientSecret: {{ required "Missing required value: agent.clientSecret is required" .Values.agent.clientSecret | quote }}
{{- end }}
{{- end }}
