{{- if and .Values.encryption.create }}
{{/* Small hack for autoamated clusters - publish the secret for git-proxy / external secrets */}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-outpost-lite.encryptionSecretName" . }}
  labels:
    {{- include "wiz-outpost-lite.labels" . | nindent 4 }}
data:
  encryptionKey.pem: {{ .Values.encryption.privateKey | b64enc | quote | required "Missing required value: encryption.privateKey is required" }}
{{- end }}
