{{- if .Values.httpProxyConfiguration.enabled }}
{{- $noProxyCommaSeparatedList := join "," .Values.httpProxyConfiguration.noProxy }}
{{- $noProxySpaceSeparatedList := join " " .Values.httpProxyConfiguration.noProxy }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.httpProxyConfiguration.name }}
  labels:
    {{- include "wiz-outpost-lite.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
data:
  {{- with .Values.httpProxyConfiguration.httpProxy }}
  httpProxy: {{ . | b64enc | quote }}
  http-proxy: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.httpProxyConfiguration.httpsProxy }}
  httpsProxy: {{ . | b64enc | quote }}
  https-proxy: {{ . | b64enc | quote }}
  {{- end }}
  {{- if .Values.httpProxyConfiguration.noProxy }}
  no-proxy-address: {{ $noProxySpaceSeparatedList | b64enc | quote }}
  no-proxy-address-cs: {{ $noProxyCommaSeparatedList | b64enc | quote }}
  noProxyAddress: {{ $noProxyCommaSeparatedList | b64enc | quote }}
  noProxyAddressSpaceSepareted: {{ $noProxySpaceSeparatedList | b64enc | quote }}
  {{- end }}
  {{- with .Values.httpProxyConfiguration.caCertificate }}
  caCertificate: {{ . | b64enc | quote }}
  {{- end }}
{{- end }}
