{{- range $values := (include "wiz-outpost-lite.runners" . | fromJson) }}
{{- with merge $values (omit $ "Values") }}
{{- if and .Values.openshift (eq .runner "container-registry") -}}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "wiz-outpost-lite.fullname" . }}-scc
  namespace: {{ .Release.Namespace }}
  labels: {{- include "wiz-outpost-lite.labels" . | nindent 4 }}
allowHostDirVolumePlugin: true
allowPrivilegedContainer: true
readOnlyRootFilesystem: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
requiredDropCapabilities: null
groups: []
priority: 0
allowedCapabilities:
  - SYS_ADMIN
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
  - '*'
users: []
volumes:
  - downwardAPI
  - emptyDir
  - hostPath
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wiz-outpost-lite.fullname" . }}-scc
  labels: {{- include "wiz-outpost-lite.labels" . | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ include "wiz-outpost-lite.fullname" . }}-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wiz-outpost-lite.fullname" . }}-scc
  labels: {{- include "wiz-outpost-lite.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: sa-{{ .runner }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "wiz-outpost-lite.fullname" . }}-scc
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end }}
{{- end }}
