apiVersion: v2
name: "wiz-opentelemetry-exporter"
description: A Helm chart for the Wiz OpenTelemetry exporter that ships Kubernetes audit logs to Wiz

type: application

version: 0.1.1

appVersion: "0.2.0"
