git:
  url: http://git-proxy.default.svc.cluster.local
  branch: master
  path: #./replaceme/
createNamespace: false
imagePullSecrets: []
image:
  repository: wiziopublic.azurecr.io
  helmController:
    name: wiz-helm-controller
    tag: v0.36.0
  sourceController:
    name: wiz-source-controller
    tag: v1.1.0
  kustomizeController:
    name: wiz-kustomize-controller
    tag: v1.1.0
affinity: {}

podAnnotaitons: {}

defaultPodAnnotations:
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"
