git:
  url: http://git-proxy.default.svc.cluster.local
  branch: master
  path: #./replaceme/
createNamespace: false
imagePullSecrets: []
image:
  repository: wiziopublic.azurecr.io
  helmController:
    name: wiz-helm-controller
    tag: v0.34.2
  sourceController:
    name: wiz-source-controller
    tag: v1.0.0-rc.5
  kustomizeController:
    name: wiz-kustomize-controller
    tag: v1.0.0-rc.4
affinity: {}

podAnnotaitons: {}

defaultPodAnnotations:
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"
