git:
  url: http://git-proxy.default.svc.cluster.local
  branch: master
  path: #./replaceme/
createNamespace: false
imagePullSecrets: []
image:
  repository: wiziopublic.azurecr.io
  helmController:
    name: wiz-helm-controller
    tag: v0.30.0-multiarch
  sourceController:
    name: wiz-source-controller
    tag: v0.35.2-multiarch
  kustomizeController:
    name: wiz-kustomize-controller
    tag: v0.34.0
affinity: {}

podAnnotaitons: {}

defaultPodAnnotations:
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"

