{{- if .Values.autoCreateConnector.enabled }}
{{- if .Values.autoCreateConnector.autoDeleteConnectorEnabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wiz-kubernetes-connector.name" . }}-delete-connector
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    rollme.proxyHash: {{ include "wiz-kubernetes-connector.proxyHash" . }}
    rollme.brokerHash: {{ include "wiz-kubernetes-connector.brokerHash" . }}
    {{- with (.Values.autoCreateConnector.deleteJobAnnotations) }}
      {{- toYaml . | nindent 4 }}
    {{- end }} 

spec:
  {{- if .Values.autoCreateConnector.useJobTTL }}
  ttlSecondsAfterFinished: 60
  {{- end }}
  manualSelector: true
  selector:
    matchLabels:
      {{- include "wiz-kubernetes-connector.selectorLabels" . | nindent 6 }}
  backoffLimit: 1
  template:
    metadata:
      {{- if (or .Values.global.podAnnotations .Values.podAnnotations .Values.autoCreateConnector.podAnnotations)}}
      annotations:
        {{- with .Values.global.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.autoCreateConnector.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        wiz.io/component: "delete-kubernetes-connector"
        {{/*
        `labels` includes `selectorLabels`
        */}}
        {{- include "wiz-kubernetes-connector.labels" . | nindent 8 }}
    spec:
      {{- with .Values.autoCreateConnector.podAdditionalSpec }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.global.podAdditionalSpec }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.autoCreateConnector.serviceAccount.name }}
      restartPolicy: "Never"
      securityContext:
        {{- if hasKey .Values.global "lowPrivilegePodSecurityPolicy" }}
        {{- toYaml .Values.global.lowPrivilegePodSecurityPolicy | nindent 8 }}
        {{- else }}
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
        {{- end }}
      volumes:
      {{- $volumes := include "wiz-kubernetes-connector.spec.common.volumes" . | trim }}
      {{- if $volumes -}}
      {{ $volumes | nindent 6 }}
      {{- end -}}
      {{- if or .Values.autoCreateConnector.customVolumes  .Values.global.customVolumes}}
      {{ with .Values.global.customVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{ with .Values.autoCreateConnector.customVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- end }}
      containers:
        - name: wiz-connector-delete
          securityContext:
            {{- if hasKey .Values.global "lowPrivilegeSecurityPolicy" }}
            {{- toYaml .Values.global.lowPrivilegeSecurityPolicy | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.global.securityContext | nindent 12 }}
            {{- end }}
          image: {{ include "wiz-broker.image" . }}
          imagePullPolicy: {{ coalesce .Values.global.image.pullPolicy .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: {{- include "wiz-kubernetes-connector.argsListDeleteConnector" . | nindent 12 }}
          env:
          {{- include "wiz-kubernetes-connector.spec.common.envVars" . | trim | nindent 10 }}
          {{- include "wiz-common.renderResources" (list .Values.resources (index .Values.global "wiz-kubernetes-connector" "resources")) | nindent 10 }}
          volumeMounts:
          {{- include "wiz-kubernetes-connector.spec.common.volumeMounts" . | trim | nindent 10 }}
          {{- if or .Values.autoCreateConnector.customVolumeMounts .Values.global.customVolumeMounts }}
          {{- with .Values.autoCreateConnector.customVolumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end -}}
          {{- with .Values.global.customVolumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}            
      {{- with (coalesce .Values.global.nodeSelector .Values.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (coalesce .Values.global.affinity .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if (or .Values.global.tolerations .Values.tolerations) }}
      tolerations:
        {{- with .Values.global.tolerations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
