{{- if .Values.autoDeleteConnector.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wiz-kubernetes-connector.name" . }}-delete-connector-{{ randNumeric 5  }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

spec:
  manualSelector: true
  selector:
    matchLabels:
      {{- include "wiz-kubernetes-connector.selectorLabels" . | nindent 6 }}
  backoffLimit: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{/*
        `labels` includes `selectorLabels`
        */}}
        {{- include "wiz-kubernetes-connector.labels" . | nindent 8 }}
    spec:
      hostAliases:  # delete me!
      - ip: "192.168.65.2" # check minikube host ip!
        hostnames: # delete me!
          - "auth" # delete me!
          - "agent-gateway" # delete me!
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.autoCreateConnector.serviceAccount.name }}
      restartPolicy: "Never"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.autoCreateConnector.customVolumes }}
      volumes:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: wiz-connector-delete
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command: ["wiz-broker"]
          args: [
            "delete-kubernetes-connector",
            "--secrets-namespace", 
            {{ .Release.Namespace | quote }},
            {{- if .Values.broker.enabled }}
            "--output-secret-name",
            {{- include "wiz-kubernetes-connector.connectorSecretName" . | trim | quote | nindent 12 }},
            {{- end }}
            ]
          env:
          - name: DEV # todo: delete me
            value: "true"
          - name: LOG_DEBUG # todo: delete me
            value: "true"
          - name: WIZ_API_HOSTNAME # todo: delete me
            value: "host.minikube.internal"
          - name: WIZ_API_PORT # todo: delete me
            value: "3103"
          {{- if .Values.autoDeleteConnector.podCustomEnvironmentVariablesFile }}
          - name: CLI_ENV_FILE
            value: {{ .Values.autoDeleteConnector.podCustomEnvironmentVariablesFile }}
          - name: USE_CLI_ENV_FILE
            value: "true"
          {{- end }}
          {{- if not .Values.wizApiToken.usePodCustomEnvironmentVariablesFile }}
          - name: WIZ_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "wiz-kubernetes-connector.apiTokenSecretName" . | trim }}
                key: clientId
                optional: false
          - name: WIZ_CLIENT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "wiz-kubernetes-connector.apiTokenSecretName" . | trim }}
                key: clientToken
                optional: false
          {{- end }}
          - name: WIZ_ENV
            value: {{ .Values.wizApiToken.clientEndpoint | quote }}
          {{- if .Values.httpProxyConfiguration.enabled }}
          - name: HTTP_PROXY
            valueFrom:
              secretKeyRef:
                name: {{ include "wiz-kubernetes-connector.proxySecretName" . | trim }}
                key: httpProxy
                optional: false
          - name: HTTPS_PROXY
            valueFrom:
              secretKeyRef:
                name: {{ include "wiz-kubernetes-connector.proxySecretName" . | trim }}
                key: httpsProxy
                optional: false
          - name: NO_PROXY
            valueFrom:
              secretKeyRef:
                name: {{ include "wiz-kubernetes-connector.proxySecretName" . | trim }}
                key: noProxyAddress
                optional: false
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.autoCreateConnector.customVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}            
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}        

{{- end }}
