{{- if .Values.broker.enabled }}
{{- if .Values.wizConnector.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-kubernetes-connector.connectorSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- with .Values.wizConnector.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- include "wiz-kubernetes-connector.wizConnectorSecretData" . | nindent 2 }}
{{- end }}
{{- end }}

{{- if and .Values.wizApiToken.createSecret .Values.autoCreateConnector.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-kubernetes-connector.apiTokenSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-1"
    {{- with .Values.wizApiToken.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  clientId: {{ required "Missing required value wizApiToken.clientId is required" .Values.wizApiToken.clientId | b64enc | quote }}
  clientToken: {{ required "Missing required value: wizApiToken.clientToken is required" .Values.wizApiToken.clientToken | b64enc | quote }}
{{- end }}
