{{- if .Values.wizConnector.createSecret }}
{{- $secretName := include "wiz-kubernetes-connector.connectorSecretName" . | trim}}
{{- if not (lookup "v1" "Secret" .Release.Namespace $secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-kubernetes-connector.connectorSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- with .Values.wizConnector.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- include "wiz-kubernetes-connector.wizConnectorSecretData" . | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if .Values.wizConnector.deleteSecret }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wiz-kubernetes-connector.connectorSecretName" . | trim }}-deletion-job
  namespace: {{ .Release.Namespace | quote }}
  annotations:
  "helm.sh/hook": post-delete
  "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: "Never"
      serviceAccountName: {{ .Values.autoCreateConnector.serviceAccount.name }}
      containers:
        - name: secret-deletion-container
          image: "{{ coalesce .Values.global.image.registry .Values.image.registry }}/{{ coalesce .Values.global.image.repository .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - echo here && kubectl delete secret releases-connector -n wiz
{{- end }}