{{- if .Values.httpProxyConfiguration.enabled }}
{{- if .Values.httpProxyConfiguration.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-kubernetes-connector.proxySecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
data:
  httpProxy: {{ .Values.httpProxyConfiguration.httpProxy | b64enc | quote }}
  httpsProxy: {{ .Values.httpProxyConfiguration.httpsProxy | b64enc | quote }}
  noProxyAddress: {{ .Values.httpProxyConfiguration.noProxyAddress | b64enc | quote }}
{{- end }}
{{- end }}
