{{- if and (not (empty .Values.httpProxyConfiguration.httpsProxy)) (eq .Values.httpProxyConfiguration.enabled false) }}
  {{- fail "Error: httpsProxy is set but httpProxyConfiguration.enabled is false. Please enable the proxy configuration or unset httpsProxy." }}
{{- end }}

{{- if and .Values.httpProxyConfiguration.enabled .Values.httpProxyConfiguration.create }}
  {{- if hasPrefix "https://" .Values.httpProxyConfiguration.httpsProxy }}
    {{- fail "Error: httpsProxy must start with 'http://', https or any other protocol is not supported." }}
  {{- end }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-kubernetes-connector.proxySecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- with .Values.httpProxyConfiguration.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
stringData:
  http_proxy: {{ .Values.httpProxyConfiguration.httpProxy | quote }}
  https_proxy: {{ .Values.httpProxyConfiguration.httpsProxy | quote }}
  no_proxy: {{ .Values.httpProxyConfiguration.noProxyAddress | quote }}
  httpProxy: {{ .Values.httpProxyConfiguration.httpProxy | quote }}
  httpsProxy: {{ .Values.httpProxyConfiguration.httpsProxy | quote }}
  noProxyAddress: {{ .Values.httpProxyConfiguration.noProxyAddress | quote }}
{{- end }}
