{{- if .Values.wizConnector.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-kubernetes-connector.connectorSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- with .Values.wizConnector.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- include "wiz-kubernetes-connector.wizConnectorSecretData" . | nindent 2 }}
{{- end }}