{{- if and .Values.httpProxyConfiguration.enabled .Values.httpProxyConfiguration.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-kubernetes-connector.proxySecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    {{- with .Values.httpProxyConfiguration.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
data:
  httpProxy: {{ .Values.httpProxyConfiguration.httpProxy | b64enc | quote }}
  httpsProxy: {{ .Values.httpProxyConfiguration.httpsProxy | b64enc | quote }}
  noProxyAddress: {{ .Values.httpProxyConfiguration.noProxyAddress | b64enc | quote }}
{{- end }}
