{{- if and .Values.global.autoCreateConnector .Values.autoCreateConnector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.autoCreateConnector.serviceAccount.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  {{- with .Values.autoCreateConnector.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if and .Values.global.autoCreateConnector .Values.autoCreateConnector.serviceAccount.createRbac }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.autoCreateConnector.serviceAccount.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ include "wiz-kubernetes-connector.connectorSecretName" . | trim | quote }}]
    verbs: ["update", "get"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [
      {{ include "wiz-kubernetes-connector.apiTokenSecretName" . | trim | quote }},
      {{ include "wiz-kubernetes-connector.clusterReaderToken" . | quote }},
    ]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.autoCreateConnector.serviceAccount.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ .Values.autoCreateConnector.serviceAccount.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.autoCreateConnector.serviceAccount.name }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
