{{- if  and .Values.refreshToken.installRbac .Values.refreshToken.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.refreshToken.serviceAccount.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.refreshToken.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.refreshToken.serviceAccount.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames: ["{{ .Values.clusterReader.serviceAccount.name }}"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ include "wiz-kubernetes-connector.connectorSecretName" . | trim | quote }}]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.refreshToken.serviceAccount.name }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ .Values.refreshToken.serviceAccount.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.refreshToken.serviceAccount.name }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
