{{- if .Values.clusterReader.installRbac }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.clusterReader.serviceAccount.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- with .Values.clusterReader.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- if not .Values.refreshToken.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterReader.serviceAccount.name }}-token
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    kubernetes.io/service-account.name: {{ .Values.clusterReader.serviceAccount.name }}
    {{- with .Values.clusterReader.secret.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/service-account-token
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterReader.serviceAccount.name }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
  {{- with .Values.clusterReader.serviceAccount.rules }}
rules:
{{ toYaml . | indent 2 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterReader.serviceAccount.name }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ .Values.clusterReader.serviceAccount.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.clusterReader.serviceAccount.name }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
