{{- if .Values.broker.enabled }}
{{ $mountPath := "/etc/connectorData" }}
{{ $connectorDataFileName := "data" }}
{{ $connectorDataFilePath := printf "%s/%s" $mountPath "data" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiz-kubernetes-connector.name" . }}-broker
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-kubernetes-connector.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "wiz-kubernetes-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{/*
        `labels` includes `selectorLabels`
        */}}
        {{- include "wiz-kubernetes-connector.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.broker.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: connector-data
          secret:
            secretName: {{ include "wiz-kubernetes-connector.connectorSecretName" . | trim }}
            items:
            - key: connectorData
              path: {{ $connectorDataFileName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: connector-data
            mountPath: {{ $mountPath }}
            readOnly: true
          args: [
            {{ $connectorDataFilePath }}
          ]
          env:
          - name: TARGET_IP
            value: {{ .Values.broker.targetIp }}
          {{- if .Values.httpProxyConfiguration.enabled }}
          - name: HTTP_PROXY
            valueFrom:
              secretKeyRef:
                name: {{ include "wiz-kubernetes-connector.proxySecretName" . | trim }}
                key: httpsProxy # The frp project supports only HTTP_PROXY, it uses it for both http and https.  Our broker always uses https, so we're using the httpsProxy value here (See: https://github.com/fatedier/frp/#connecting-to-frps-via-http-proxy)
          {{- end }}
{{- end }}
