apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "flux2.labels" . | nindent 4 }}
    control-plane: controller
  name: kustomize-controller
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-controller
  template:
    metadata:
      annotations:
        {{- if .Values.podAnnotations }}
        {{- with merge .Values.defaultPodAnnotations .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- else }}
        {{- toYaml .Values.defaultPodAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app: kustomize-controller
    spec:
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - --watch-all-namespaces
            - --log-level=error
            - --log-encoding=json
            - --enable-leader-election
          env:
            - name: RUNTIME_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: "{{ .Values.image.repository }}/{{ .Values.image.kustomizeController.name }}:{{ .Values.image.kustomizeController.tag }}"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          name: manager
          ports:
            - containerPort: 9440
              name: healthz
              protocol: TCP
            - containerPort: 8080
              name: http-prom
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /tmp
              name: temp
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        fsGroup: 1337
      serviceAccountName: kustomize-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - emptyDir: {}
          name: temp
