---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: outpost-state
spec:
  interval: 3m0s
  ref:
    branch: {{ required "branch is required" .Values.git.branch }}
  url: {{ required "git.url is required" .Values.git.url }}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: outpost-state
spec:
  interval: 10m0s
  path: {{ required "git.path is required" .Values.git.path }}
  prune: true
  sourceRef:
    kind: GitRepository
    name: outpost-state
