{{- if and .Values.httpProxyConfiguration.enabled .Values.httpProxyConfiguration.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-network-analyzer.proxySecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- with .Values.httpProxyConfiguration.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wiz-network-analyzer.labels" . | nindent 4 }}
stringData:
  httpsProxy: {{ .Values.httpProxyConfiguration.httpsProxy | quote }}
  noProxyAddress: {{ .Values.httpProxyConfiguration.noProxyAddress | quote }}
{{- end }}
