{{- if and .Values.caCertificate.enabled .Values.caCertificate.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-network-analyzer.caSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- with .Values.caCertificate.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "wiz-network-analyzer.labels" . | nindent 4 }}
stringData:
  ca.crt: {{ .Values.caCertificate.certificate | quote }}
{{- end }}
