{{- if and .Values.wizApiToken.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-network-analyzer.apiTokenSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-network-analyzer.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- with.Values.wizApiToken.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  clientId: {{ required "Missing required value wizApiToken.clientId is required" .Values.wizApiToken.clientId | quote }}
  clientToken: {{ required "Missing required value: wizApiToken.clientToken is required" .Values.wizApiToken.clientToken | quote }}
{{- end }}
