{{- if and (not (empty .Values.httpProxyConfiguration.httpsProxy)) (eq .Values.httpProxyConfiguration.enabled false) }}
  {{- fail "Error: httpsProxy is set but httpProxyConfiguration.enabled is false. Please enable the proxy configuration or unset httpsProxy." }}
{{- end }}

{{- if and .Values.httpProxyConfiguration.enabled .Values.httpProxyConfiguration.create }}
  {{- if and (hasPrefix "http://" .Values.httpProxyConfiguration.httpsProxy) .Values.httpProxyConfiguration.clientCertificate }}
    {{- fail "Error: Client certificate is only supported for HTTPS proxies. Please remove clientCertificate or use an HTTPS proxy." }}
  {{- end }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-broker.proxySecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  {{ if .Values.httpProxyConfiguration.annotations }}
  annotations:
    {{- if (index .Values "wiz-broker" "enabled") }} # Secret used by per-install hook in wiz-kubernetes-connector
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- end }}
    {{- with .Values.httpProxyConfiguration.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
stringData:
  httpProxy: {{ .Values.httpProxyConfiguration.httpProxy | quote }}
  httpsProxy: {{ .Values.httpProxyConfiguration.httpsProxy | quote }}
  noProxyAddress: {{ .Values.httpProxyConfiguration.noProxyAddress | quote }}
  clientCertificate: {{ .Values.httpProxyConfiguration.clientCertificate | quote }}
{{- end }}
