{{- if .Values.global.broker.enabled }}
{{- if and .Values.global.wizConnector.createSecret .Values.global.broker.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-broker.connectorSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "wiz-broker.wizConnectorSecretData" . | nindent 2 }}
{{- end }}
{{- end }}

{{- if and .Values.global.wizApiToken.secret.create .Values.global.broker.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-broker.apiTokenSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
data:
  clientId: {{ required "Missing required value wizApiToken.clientId is required" .Values.global.wizApiToken.clientId | b64enc | quote }}
  clientToken: {{ required "Missing required value: wizApiToken.clientToken is required" .Values.global.wizApiToken.clientToken | b64enc | quote }}
{{- end }}
