{{- if and .Values.global.httpProxyConfiguration.enabled .Values.global.httpProxyConfiguration.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "wiz-broker.proxySecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  {{ if .Values.global.httpProxyConfiguration.annotations }}
  annotations:
    {{- if (index .Values "wiz-broker" "enabled") }} # Secret used by per-install hook in wiz-kubernetes-connector
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    {{- end }}
    {{- with .Values.global.httpProxyConfiguration.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
stringData:
  httpProxy: {{ .Values.global.httpProxyConfiguration.httpProxy | quote }}
  httpsProxy: {{ .Values.global.httpProxyConfiguration.httpsProxy | quote }}
  noProxyAddress: {{ .Values.global.httpProxyConfiguration.noProxyAddress | quote }}
  caCertificate: {{ .Values.global.httpProxyConfiguration.caCertificate | quote }}
  skipTlsVerify: {{ .Values.global.httpProxyConfiguration.skipTlsVerify | quote }}
{{- end }}
