{{- if .Values.global.broker.enabled }}
{{- if and .Values.global.wizConnector.createSecret .Values.global.broker.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-broker.connectorSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.wizConnector.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  connectorData: {{ include "wiz-broker.wizConnectorSecretData" . | fromYaml | toJson | b64enc | quote }}
{{- end }}

{{- if and .Values.global.broker.caCertificate.enabled .Values.global.broker.caCertificate.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-broker.caCertificateSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.broker.caCertificate.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  caCertificate: {{ .Values.global.broker.caCertificate.pem | b64enc | quote }}
{{- end }}

{{- if and .Values.global.broker.mtls.enabled .Values.global.broker.mtls.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-broker.mtlsSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.broker.mtls.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  certificate: {{ .Values.global.broker.mtls.certificate | b64enc | quote }}
  privateKey: {{ .Values.global.broker.mtls.privateKey | b64enc | quote }}
{{- end }}
{{- end }}

{{- if and .Values.global.wizApiToken.secret.create .Values.global.broker.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-broker.apiTokenSecretName" . | trim }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.global.wizApiToken.secret.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  clientId: {{ required "Missing required value wizApiToken.clientId is required" .Values.global.wizApiToken.clientId | b64enc | quote }}
  clientToken: {{ required "Missing required value: wizApiToken.clientToken is required" .Values.global.wizApiToken.clientToken | b64enc | quote }}
{{- end }}
