{{- if .Values.installRbac }}
{{- $rbacServiceAccountName := include "wiz-broker.rbacServiceAccountName" . -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $rbacServiceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
  {{- with .Values.rbacServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ $rbacServiceAccountName }}-token
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ $rbacServiceAccountName }}
    {{- with .Values.rbacSecret.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $rbacServiceAccountName }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $rbacServiceAccountName }}
  labels:
    {{- include "wiz-broker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ $rbacServiceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ $rbacServiceAccountName }}
  namespace: {{ .Values.namespace }}
{{- end }}
