apiVersion: v2
name: wiz-kubernetes-integration
description: A Helm chart for Kubernetes
type: application
version: 0.2.16
appVersion: ""

# Dependencies for wiz-kubernetes connector and wiz-admission-controller and wiz-sensor
dependencies:
- name: wiz-kubernetes-connector
  repository: "file://../wiz-kubernetes-connector" # Use this line to test the chart locally
  #repository: https://wiz-sec.github.io/charts
  version: ">=3.1.0"
  condition: wiz-kubernetes-connector.enabled
- name: "wiz-admission-controller"
  repository: "file://../wiz-admission-controller" # Use this line to test the chart locally
  #repository: https://wiz-sec.github.io/charts
  version:  ">=3.6.1-preview"
  condition: wiz-admission-controller.enabled
- name: wiz-sensor
  repository: "file://../wiz-sensor" # Use this line to test the chart locally
  #repository: https://wiz-sec.github.io/charts
  version: ">=1.0.4708"
  condition: wiz-sensor.enabled
