apiVersion: v2
name: wiz-kubernetes-integration
description: A Helm chart for Kubernetes
type: application
version: 0.1.79
appVersion: ""

# Dependencies for wiz-kubernetes connector and wiz-admission-controller and wiz-sensor
dependencies:
- name: wiz-kubernetes-connector
  repository: https://wiz-sec.github.io/charts
  version: ">=2.2.8"
  condition: wiz-kubernetes-connector.enabled
- name: "wiz-admission-controller"
  repository: https://wiz-sec.github.io/charts
  version:  ">=3.0.1"
  condition: wiz-admission-controller.enabled
- name: wiz-sensor
  repository: https://wiz-sec.github.io/charts
  version: ">=1.0.2304"
  condition: wiz-sensor.enabled
