{{- if .Values.httpProxyConfiguration.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.httpProxyConfiguration.name }}
  labels:
    {{- include "git-proxy.labels" . | nindent 4 }}
data:
  http-proxy: {{ .Values.httpProxyConfiguration.httpProxy | b64enc | quote }}
  https-proxy: {{ .Values.httpProxyConfiguration.httpsProxy | b64enc | quote }}
  no-proxy-address: {{ .Values.httpProxyConfiguration.noProxy | b64enc | quote }}
  no-proxy-address-cs: {{ .Values.httpProxyConfiguration.noProxyCs | b64enc | quote }}
{{- end }}
