{{- if .Values.blob.azureCreds }}
{{/* Small hack for autoamated clusters - publish the secret for git-proxy / external secrets */}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: azure-creds
  labels:
    {{- include "git-proxy.labels" . | nindent 4 }}
data:
  azure.json: {{ .Values.blob.azureCreds | toJson | b64enc | quote }}
  {{/* external secrets need each key seperately so we reference the secret via env vars */}}
  {{- range $k, $v := .Values.blob.azureCreds }}
  {{ $k }}: {{ $v | b64enc | quote}}
  {{- end }}
{{- end }}

{{- if eq .Values.storageService "objectstorage" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oci-creds
  labels:
    {{- include "git-proxy.labels" . | nindent 4 }}
data:
  oci.json: {{ .Values.objectstorage.ociCreds | toJson | b64enc | quote }}
  {{/* external secrets need each key seperately so we reference the secret via env vars */}}
  {{- range $k, $v := .Values.objectstorage.ociCreds }}
  {{ $k }}: {{ $v | b64enc | quote}}
  {{- end }}
{{- end }}
