{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "git-proxy.serviceAccountName" . }}
  labels:
    {{- include "git-proxy.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.azureWorkloadIdentityClientID }}
    azure.workload.identity/use: "true"
    {{- end }}
  
  annotations:
    {{- if .Values.serviceAccount.azureWorkloadIdentityClientID }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.azureWorkloadIdentityClientID }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
