{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "git-proxy.serviceAccountName" . }}
  labels:
    {{- include "git-proxy.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
