apiVersion: v1
kind: Service
metadata:
  name: {{ include "git-proxy.fullname" . }}
  labels:
    {{- include "git-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 3000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "git-proxy.selectorLabels" . | nindent 4 }}
---
{{- if ne .Release.Name "git-proxy" }}
apiVersion: v1
kind: Service
metadata:
  name: git-proxy
  labels:
    {{- include "git-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 3000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "git-proxy.selectorLabels" . | nindent 4 }}
{{- end }}
