{{- if eq .Values.storageService "wiz" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wiz.secretName }}
  labels:
    {{- include "git-proxy.labels" . | nindent 4 }}
stringData:
{{- if .Values.outpostId }}
  clientId: {{ required "Missing required value wiz.clientId is required" .Values.wiz.clientId | quote }}
  clientSecret: {{ required "Missing required value: wiz.clientSecret is required" .Values.wiz.clientSecret | quote }}
{{- else }}
  privateKey: {{ required "Missing required value wiz.privateKey" .Values.wiz.privateKey | quote }}
{{- end }}
{{- end }}
