{{- if eq .Values.storageService "wiz" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wiz.secretName }}
  labels:
    {{- include "git-proxy.labels" . | nindent 4 }}
stringData:
  clientId: {{ required "Missing required value wiz.clientId is required" .Values.wiz.clientId | b64enc | quote }}
  clientSecret: {{ required "Missing required value: wiz.clientSecret is required" .Values.wiz.clientSecret | b64enc | quote }}
{{- end }}
